name: Ansible Setup on EC2 workflow

on:
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  terraform:
    name: Provision Infrastructure with Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Correct use of `uses`
      
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1 
    # Set up AWS credentials for accessing EC2
    - name: Set up AWS credentials 
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

    # Run Terraform commands to provision infrastructure
    - name: Terraform Init
      working-directory: ./terraform  # Set working directory to terraform folder
      run: terraform init  # Correct use of `run`

    - name: Terraform Apply
      working-directory: ./terraform  # Set working directory to terraform folder
      run: terraform apply -auto-approve  # Correct use of `run`  
